# Generated by Django 4.0.1 on 2022-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_alter_registrationmodel_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='contact_number',
            field=models.CharField(max_length=13),
        ),
    ]
