# Generated by Django 4.0.1 on 2022-02-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_alter_registrationmodel_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
