# Generated by Django 4.0.1 on 2022-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_verifyemailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
