# Generated by Django 4.0.1 on 2022-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_registrationmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='date_of_birth',
            field=models.CharField(default='', max_length=30),
        ),
    ]
