# Generated by Django 4.0.1 on 2022-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0008_appointmentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
