# Generated by Django 4.0.1 on 2022-03-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_appointmentmodel_patient_alter_appointmentmodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='patient',
            new_name='patient_email',
        ),
    ]
