# Generated by Django 4.0.1 on 2022-03-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0010_rename_patient_appointmentmodel_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='patient_email',
            field=models.EmailField(max_length=50),
        ),
    ]
